name: Post PR Comment

on:
  workflow_run:
    workflows: ["Publish Package"]
    types: [completed]

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  post-comment:
    name: Post Validation Comment
    runs-on: {{githubRunner}}
    if: github.event.workflow_run.event == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Download validation artifact
        uses: actions/github-script@v7
        id: artifact
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });
            const match = artifacts.data.artifacts.find(a => a.name === 'validation-results');
            if (!match) {
              core.warning('No validation-results artifact found');
              core.setOutput('found', 'false');
              return;
            }
            const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: match.id,
              archive_format: 'zip',
            });
            const fs = require('fs');
            fs.writeFileSync('validation-results.zip', Buffer.from(download.data));
            core.setOutput('found', 'true');

      - name: Extract artifact
        if: steps.artifact.outputs.found == 'true'
        run: unzip -o validation-results.zip -d .

      - name: Read PR number
        if: steps.artifact.outputs.found == 'true'
        id: pr
        run: |
          if [ -f pr-number.txt ]; then
            echo "number=$(cat pr-number.txt)" >> "$GITHUB_OUTPUT"
          fi

      - name: Post comment to PR
        if: steps.pr.outputs.number != ''
        uses: ./.github/actions/pr-comment
        with:
          issue-number: ${{ steps.pr.outputs.number }}
          body-path: validation-comment.md
          comment-tag: collection-validation
