name: Post PR Comment

on:
  workflow_run:
    workflows: ["Publish Package"]
    types: [completed]

jobs:
  post-comment:
    uses: AmadeusITGroup/prompt-registry/.github/workflows/collection-post-pr-comment.yml@v1
    with:
      githubRunner: {{githubRunner}}
    secrets: inherit
