name: Publish Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    uses: AmadeusITGroup/prompt-registry/.github/workflows/collection-publish.yml@v1
    with:
      githubRunner: {{githubRunner}}
    secrets: inherit
