name: Post Validation Comment
description: Create or update a validation comment on a pull request

inputs:
  issue-number:
    description: PR/Issue number to comment on
    required: true
  body-path:
    description: Path to file containing comment body
    required: false
    default: validation-comment.md
  comment-tag:
    description: Hidden tag used to identify and update the comment
    required: false
    default: collection-validation
  github-token:
    description: GitHub token for API authentication
    required: false
    default: ${{ github.token }}

outputs:
  comment-posted:
    description: Whether the comment was successfully posted (true/false)
    value: ${{ steps.post.outputs.comment-posted }}

runs:
  using: composite
  steps:
    - name: Post comment
      id: post
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
        BODY_PATH: ${{ inputs.body-path }}
        COMMENT_TAG: ${{ inputs.comment-tag }}
      run: |
        if [ ! -f "$BODY_PATH" ]; then
          echo "::warning::No $BODY_PATH found, skipping PR comment"
          exit 0
        fi

        BODY=$(cat "$BODY_PATH")
        BODY="$BODY"$'\n\n'"<!-- $COMMENT_TAG -->"

        COMMENT_ID=$(gh api \
          "repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER/comments" \
          --jq ".[] | select(.body | contains(\"<!-- $COMMENT_TAG -->\")) | .id" \
          2>/dev/null | head -1) || true

        post_comment() {
          if [ -n "$COMMENT_ID" ]; then
            gh api \
              --method PATCH \
              "repos/$GITHUB_REPOSITORY/issues/comments/$COMMENT_ID" \
              -f body="$BODY" || return $?
            echo "Updated comment $COMMENT_ID"
          else
            gh api \
              --method POST \
              "repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER/comments" \
              -f body="$BODY" || return $?
            echo "Created new comment"
          fi
        }

        if post_comment 2>gh_error.tmp; then
          echo "comment-posted=true" >> "$GITHUB_OUTPUT"
        else
          ERROR=$(cat gh_error.tmp)
          if echo "$ERROR" | grep -q "403"; then
            echo "::warning::Could not post PR comment (403 Forbidden). This may be expected for fork PRs. Writing results to job summary instead."
            cat "$BODY_PATH" >> "$GITHUB_STEP_SUMMARY"
            echo "comment-posted=false" >> "$GITHUB_OUTPUT"
          else
            echo "::error::Failed to post PR comment: $ERROR"
            exit 1
          fi
        fi
